Abdul/nft metadata json
holaplex/metaplex-indexer pull request #68
Opened 2022-01-21 22:30 UTC by imabdulbasit

Metadata from URI is parsed and inserted into database
tables created: 
metadata_jsons
attributes
files
metadata_collections

2022-01-23 22:21 UTC, kespinola submitted a review, later dismissed
This looks good to me. Only items that come up are indexes and we arent capturing the change states of metadata json since the uri field of nft is mutable. Items to think about in the future.

2022-01-24 14:30 UTC, imabdulbasit commented
> This looks good to me. Only items that come up are indexes and we arent capturing the change states of metadata json since the uri field of nft is mutable. Items to think about in the future.

So one metadata_address has one fingerprint, a check can added if fingerprint is different for a metadata_address

2022-01-24 15:12 UTC, kespinola commented
Notes from initial testing:

```
metaplex-indexer=# SELECT COUNT(*) FROM metadata_jsons;;
 count
-------
  4594
(1 row)

metaplex-indexer=# SELECT COUNT(*) FROM metadatas;;
 count
-------
 10580
(1 row)
```

In a fresh run about half metadata have an associated json.


```
[2022-01-24T15:05:37Z DEBUG reqwest::async_impl::client] response '200 OK' for https://bqrzzb3nqwavyhn7c6cpvoloojoh3cvrf52emv7b5ldzuuiwazaa.arweave.net/DCOch22FgVwdvxeE-rluclx9irEvdEZX4erHmlEWBkA/
[2022-01-24T15:08:32Z ERROR metaplex_indexer::entry] Job MetadataUri(5btasmbUigzK7wstC1UpasrLHEVC6cYPxwo44KupXxCr, "https://arweave.net/R1U8tgnWrahVf2KpaISSGWWxbjgHRirQKyqmMn6uPG0") failed: Metadata JSON request failed

    Caused by:
        0: error sending request for url (https://arweave.net/R1U8tgnWrahVf2KpaISSGWWxbjgHRirQKyqmMn6uPG0): error trying to connect: connection closed via error
        1: error trying to connect: connection closed via error
        2: connection closed via error
```

Error with connection timeout to arweave.

Don't believe I had our CDNs in place trying again with those.

2022-01-24 21:51 UTC, ray-kast requested changes
I think the merge from dev generated some broken diffs, the entire PR likely needs to be rebased onto the new dev.

2022-01-24 21:51 UTC, ray-kast commented on crates/core/src/lib.rs
> +    #[clap(short, long, default_value_t = 3000, env = "PORT")]
```suggestion
    #[clap(short, long, default_value_t = 3000, env)]
```
The `= "PORT"` should be implicit, was this added back for a reason?

2022-01-24 21:51 UTC, ray-kast commented on crates/core/src/db/models.rs
> +/// A row in 'metadata_collection' table
```suggestion
/// A row in the `metadata_collections` table
```

2022-01-24 21:51 UTC, ray-kast commented on crates/indexer/Cargo.toml
> +clap = "3.0.0-beta.5"
```suggestion
```
This dependency was removed in another branch.

2022-01-24 21:51 UTC, ray-kast commented on crates/indexer/src/bits/metadata_uri.rs
> +async fn process_async<'a>(
This function has some linter warnings that should be addressed.

2022-01-24 21:51 UTC, ray-kast commented on crates/indexer/src/bits/token_account.rs
> -}
Why is this removal in this PR?

2022-01-25 13:55 UTC, kespinola commented
having some git problems so moving over to the fork of this pr directly into dev. commits retained but was hoping to merge here first.

https://github.com/holaplex/metaplex-indexer/pull/79

2022-01-25 13:55 UTC, closed without merging